services:
  nginx:
    image: nginx:1.22-alpine
    container_name: nginx-${PROJECT_NAME}
    ports:
      - "${HOST_NGINX_PORT}:80"
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - symfony_network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-${PROJECT_NAME}
    volumes:
      - ./:/code
      - var_data:/code/var
    networks:
      - symfony_network
  database:
    image: mysql:8.2
    container_name: mysql-${PROJECT_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "${HOST_MYSQL_PORT}:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - symfony_network
  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma-${PROJECT_NAME}
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "${HOST_PMA_PORT}:80"
    networks:
      - symfony_network
  mailhog:
    build:
      context: .
      dockerfile: Dockerfile.mailhog
    container_name: mailhog-${PROJECT_NAME}
    ports:
      - "${HOST_SMTP_PORT}:1025"   # Port SMTP
      - "${HOST_WEBMAILHOG_PORT}:8025"   # Interface web
    networks:
      - symfony_network

volumes:
  data:
  var_data:

networks:
  symfony_network:
